<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'permission_access',],
            ['id' => 3, 'title' => 'permission_create',],
            ['id' => 4, 'title' => 'permission_edit',],
            ['id' => 5, 'title' => 'permission_view',],
            ['id' => 6, 'title' => 'permission_delete',],
            ['id' => 7, 'title' => 'role_access',],
            ['id' => 8, 'title' => 'role_create',],
            ['id' => 9, 'title' => 'role_edit',],
            ['id' => 10, 'title' => 'role_view',],
            ['id' => 11, 'title' => 'role_delete',],
            ['id' => 12, 'title' => 'user_access',],
            ['id' => 13, 'title' => 'user_create',],
            ['id' => 14, 'title' => 'user_edit',],
            ['id' => 15, 'title' => 'user_view',],
            ['id' => 16, 'title' => 'user_delete',],
            ['id' => 17, 'title' => 'team_access',],
            ['id' => 18, 'title' => 'team_create',],
            ['id' => 19, 'title' => 'team_edit',],
            ['id' => 20, 'title' => 'team_view',],
            ['id' => 21, 'title' => 'team_delete',],
            ['id' => 22, 'title' => 'task_status_access',],
            ['id' => 23, 'title' => 'task_status_create',],
            ['id' => 24, 'title' => 'task_status_edit',],
            ['id' => 25, 'title' => 'task_status_view',],
            ['id' => 26, 'title' => 'task_status_delete',],
            ['id' => 27, 'title' => 'task_management_access',],
            ['id' => 28, 'title' => 'task_management_create',],
            ['id' => 29, 'title' => 'task_management_edit',],
            ['id' => 30, 'title' => 'task_management_view',],
            ['id' => 31, 'title' => 'task_management_delete',],
            ['id' => 32, 'title' => 'task_tag_access',],
            ['id' => 33, 'title' => 'task_tag_create',],
            ['id' => 34, 'title' => 'task_tag_edit',],
            ['id' => 35, 'title' => 'task_tag_view',],
            ['id' => 36, 'title' => 'task_tag_delete',],
            ['id' => 37, 'title' => 'task_access',],
            ['id' => 38, 'title' => 'task_create',],
            ['id' => 39, 'title' => 'task_edit',],
            ['id' => 40, 'title' => 'task_view',],
            ['id' => 41, 'title' => 'task_delete',],
            ['id' => 42, 'title' => 'task_calendar_access',],
            ['id' => 43, 'title' => 'task_calendar_create',],
            ['id' => 44, 'title' => 'task_calendar_edit',],
            ['id' => 45, 'title' => 'task_calendar_view',],
            ['id' => 46, 'title' => 'task_calendar_delete',],
            ['id' => 47, 'title' => 'program_access',],
            ['id' => 48, 'title' => 'cataward_access',],
            ['id' => 49, 'title' => 'cataward_create',],
            ['id' => 50, 'title' => 'cataward_edit',],
            ['id' => 51, 'title' => 'cataward_view',],
            ['id' => 52, 'title' => 'cataward_delete',],
            ['id' => 53, 'title' => 'award_access',],
            ['id' => 54, 'title' => 'award_create',],
            ['id' => 55, 'title' => 'award_edit',],
            ['id' => 56, 'title' => 'award_view',],
            ['id' => 57, 'title' => 'award_delete',],
            ['id' => 58, 'title' => 'project_access',],
            ['id' => 59, 'title' => 'project_create',],
            ['id' => 60, 'title' => 'project_edit',],
            ['id' => 61, 'title' => 'project_view',],
            ['id' => 62, 'title' => 'project_delete',],
            ['id' => 63, 'title' => 'program_create',],
            ['id' => 64, 'title' => 'program_edit',],
            ['id' => 65, 'title' => 'program_view',],
            ['id' => 66, 'title' => 'program_delete',],
            ['id' => 67, 'title' => 'notatki_access',],
            ['id' => 68, 'title' => 'catnote_access',],
            ['id' => 69, 'title' => 'catnote_create',],
            ['id' => 70, 'title' => 'catnote_edit',],
            ['id' => 71, 'title' => 'catnote_view',],
            ['id' => 72, 'title' => 'catnote_delete',],
            ['id' => 73, 'title' => 'note_access',],
            ['id' => 74, 'title' => 'note_create',],
            ['id' => 75, 'title' => 'note_edit',],
            ['id' => 76, 'title' => 'note_view',],
            ['id' => 77, 'title' => 'note_delete',],
            ['id' => 78, 'title' => 'baza_firm_access',],
            ['id' => 79, 'title' => 'year_access',],
            ['id' => 80, 'title' => 'year_create',],
            ['id' => 81, 'title' => 'year_edit',],
            ['id' => 82, 'title' => 'year_view',],
            ['id' => 83, 'title' => 'year_delete',],
            ['id' => 84, 'title' => 'vivodeship_access',],
            ['id' => 85, 'title' => 'vivodeship_create',],
            ['id' => 86, 'title' => 'vivodeship_edit',],
            ['id' => 87, 'title' => 'vivodeship_view',],
            ['id' => 88, 'title' => 'vivodeship_delete',],
            ['id' => 89, 'title' => 'trade_access',],
            ['id' => 90, 'title' => 'trade_create',],
            ['id' => 91, 'title' => 'trade_edit',],
            ['id' => 92, 'title' => 'trade_view',],
            ['id' => 93, 'title' => 'trade_delete',],
            ['id' => 94, 'title' => 'company_access',],
            ['id' => 95, 'title' => 'company_create',],
            ['id' => 96, 'title' => 'company_edit',],
            ['id' => 97, 'title' => 'company_view',],
            ['id' => 98, 'title' => 'company_delete',],
            ['id' => 100, 'title' => 'programy_access',],
            ['id' => 101, 'title' => 'internal_notification_access',],
            ['id' => 102, 'title' => 'internal_notification_create',],
            ['id' => 103, 'title' => 'internal_notification_edit',],
            ['id' => 104, 'title' => 'internal_notification_view',],
            ['id' => 105, 'title' => 'internal_notification_delete',],
            ['id' => 106, 'title' => 'ogłoszenium_access',],
            ['id' => 107, 'title' => 'catadvert_access',],
            ['id' => 108, 'title' => 'catadvert_create',],
            ['id' => 109, 'title' => 'catadvert_edit',],
            ['id' => 110, 'title' => 'catadvert_view',],
            ['id' => 111, 'title' => 'catadvert_delete',],
            ['id' => 112, 'title' => 'advert_access',],
            ['id' => 113, 'title' => 'advert_create',],
            ['id' => 114, 'title' => 'advert_edit',],
            ['id' => 115, 'title' => 'advert_view',],
            ['id' => 116, 'title' => 'advert_delete',],
            ['id' => 117, 'title' => 'nominated_access',],
            ['id' => 118, 'title' => 'nominated_create',],
            ['id' => 119, 'title' => 'nominated_edit',],
            ['id' => 120, 'title' => 'nominated_view',],
            ['id' => 121, 'title' => 'nominated_delete',],
            ['id' => 122, 'title' => 'organization_access',],
            ['id' => 123, 'title' => 'organization_create',],
            ['id' => 124, 'title' => 'organization_edit',],
            ['id' => 125, 'title' => 'organization_view',],
            ['id' => 126, 'title' => 'organization_delete',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
